train:
- E:/robust-satellite-detection/data/CZ_B/images/train
- E:/robust-satellite-detection/data/CZ_C/images/train
val:
- E:/robust-satellite-detection/data/CZ_B/images/val
- E:/robust-satellite-detection/data/CZ_C/images/val
test:
- E:/robust-satellite-detection/data/CZ_A/images/test
nc: 8
names:
- Building
- Small Car
- Truck
- Bus
- Cargo Truck
- Shipping Container
- Vehicle Lot
- Shed
